### ISSUE TITLE
DF1 - LaTeX compile issue

### ISSUE THREAD

**Issue by AbbyANoble** [StevenClontz/cal1-tbil-2021-checkit#10]
Answer of part (a) needs to either switch to `\[` and` \]` or combine everything between the the` \( `and `\)` to one line. Causing errors currently. Begins at line 109 in the code generated by CheckIt:

![image](https://user-images.githubusercontent.com/85640990/144112912-7752e481-6ba1-48a3-88f8-fcc59d16a115.png)

**Comment by StevenClontz** [comment]
This will be solved when https://github.com/StevenClontz/checkit/issues/58 is solved.

**Comment by StevenClontz** [comment]
Stopgap solution in 7fe798e fixes this with current CheckIt
