### ISSUE TITLE
DF7 - product rule appearance

### ISSUE THREAD

**Issue by AbbyANoble** [StevenClontz/cal1-tbil-2021-checkit#13]
from Francesca - 
Some of the randomized problems do not use the product rule in both parts, some do. I would suggest to randomize so that part a does not require the product rule but has two terms with dy/dx, part b has the product rule but only one dy/dx

**Comment by fragandi** [comment]
I have changed the code so that this feature is implemented. One line of the code can be uncommented to possibly produce harder problems as in the original version.
