### ISSUE TITLE
AD2 Incorrect answer + confusing last part

### ISSUE THREAD

**Issue by fragandi** [StevenClontz/cal1-tbil-2021-checkit#16]
Issues
1. There are mistakes in the solution. Using a linear approximation, every time you have p’’>0 you have an underestimate and when p’’<0 you have an overestimate. This is not the case in the answer key
2. In the last part, I think we should eliminate the additional information about the concavity before and after the point, especially because this seems to imply that p’’=0 where we compute the linear approx. Keep the graphing but either with a function always cu or cd.

**Comment by StevenClontz** [comment]
how does this look?

![image](https://user-images.githubusercontent.com/1559632/146266574-75404678-16e2-42a5-b87a-a18071c6bef6.png)

**Comment by StevenClontz** [comment]
with @fragandi edits:

![image](https://user-images.githubusercontent.com/1559632/146267151-8b1cc32c-dab5-4fae-bb38-be8d9c099a56.png)

**Comment by fragandi** [comment]
TO-DO (Francesca) Check consistency with terminology in book local linearization vs linearization

**Comment by StevenClontz** [comment]
Implemented at 229a612 - leaving this open so @fragandi can handle "[local] linearization" issue as she sees fit.

**Comment by fragandi** [comment]
changed to linearization for consistency
