### ISSUE TITLE
DF3 - answer issue

### ISSUE THREAD

**Issue by AbbyANoble** [StevenClontz/cal1-tbil-2021-checkit#9]
Answer not calculated correctly for some of these. Not sure what seed it was taken from because I copy/pasted only part of the LaTeX code, not all of it. I *think* I remember this happening before but it's 2021 and all bets are off on me remembering things correctly any more. 

<img width="779" alt="Screen Shot 2021-11-18 at 4 17 04 PM" src="https://user-images.githubusercontent.com/85640990/142498492-b8edd169-97dd-4e2e-955a-ba8c527e35f0.png">

**Comment by StevenClontz** [comment]
Honestly this one's worth refactoring altogether; I'm about to be made a liar again (per today's discussion) because I'll probably end up fixing this by using Sage's `.diff()` method rather than coding the differentiation logic myself.
